// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/v1",
  "paths": {
    "/categories": {
      "get": {
        "description": "It returns a list of nested objects which contains all categories and sub-categories required to create menu",
        "tags": [
          "menu"
        ],
        "summary": "Get menu items for the app",
        "operationId": "CategoryList",
        "responses": {
          "200": {
            "description": "List of Categories",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Category"
      }
    },
    "Category": {
      "type": "object",
      "properties": {
        "bcId": {
          "type": "integer"
        },
        "bcImageUrl": {
          "type": "string"
        },
        "bcIsActive": {
          "type": "boolean"
        },
        "bcName": {
          "type": "string"
        },
        "subCategories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubCategory"
          }
        }
      }
    },
    "SubCategory": {
      "type": "object",
      "properties": {
        "scId": {
          "type": "integer"
        },
        "scImageUrl": {
          "type": "string"
        },
        "scIsActive": {
          "type": "boolean"
        },
        "scName": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/v1",
  "paths": {
    "/categories": {
      "get": {
        "description": "It returns a list of nested objects which contains all categories and sub-categories required to create menu",
        "tags": [
          "menu"
        ],
        "summary": "Get menu items for the app",
        "operationId": "CategoryList",
        "responses": {
          "200": {
            "description": "List of Categories",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Category"
      }
    },
    "Category": {
      "type": "object",
      "properties": {
        "bcId": {
          "type": "integer"
        },
        "bcImageUrl": {
          "type": "string"
        },
        "bcIsActive": {
          "type": "boolean"
        },
        "bcName": {
          "type": "string"
        },
        "subCategories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubCategory"
          }
        }
      }
    },
    "SubCategory": {
      "type": "object",
      "properties": {
        "scId": {
          "type": "integer"
        },
        "scImageUrl": {
          "type": "string"
        },
        "scIsActive": {
          "type": "boolean"
        },
        "scName": {
          "type": "string"
        }
      }
    }
  }
}`))
}
